export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILED = 'FETCH_GENRES_FAILED';

export const SET_SELECTED_GENRES = 'SET_SELECTED_GENRES';
export const SET_SELECTED_GENRES_ID = 'SET_SELECTED_GENRES_ID';

export const UPDATE_GENRES = 'UPDATE_GENRES';
