export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const SET_CURRENT_PAGE_MOVIES = 'SET_CURRENT_PAGE_MOVIES';

export const FETCH_MOVIES_GENRES = 'FETCH_MOVIES_GENRES';
export const FETCH_MOVIES_GENRES_SUCCESS = 'FETCH_MOVIES_GENRES_SUCCES';
export const FETCH_MOVIES_GENRES_FAILED = 'FETCH_MOVIES_GENRES_FAILED';


export const SET_MOVIES_SELECTED_GENRES= 'SET_MOVIES_SELECTED_GENRES';

export const SET_MOVIES_SELECTED_GENRES_ID = 'SET_MOVIES_SELECTED_GENRES_ID';

export const UPDATE_MOVIES_GENRES = 'UPDATE_MOVIES_GENRES';

