export const SET_KEYWORD = "SET_KEYWORD";
export const SET_TYPE = "SET_TYPE";


export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILED = "FETCH_SEARCH_FAILED";

export const SET_CURRENT_PAGE_SEARCH = "SET_CURRENT_PAGE_SEARCH";