export const FECTH_TRENDING = 'FECTH_TRENDING';
export const FECTH_TRENDING_SUCCESS = 'FECTH_TRENDING_SUCCESS';
export const FECTH_TRENDING_FAILED = 'FECTH_TRENDING_FAILED';

export const SET_TRENDING_CURRENT_PAGE = 'SET_TRENDING_CURRENT_PAGE';

