export const FETCH_TVSERIES = 'FETCH_TVSERIES';
export const FETCH_TVSERIES_SUCCESS = 'FETCH_TVSERIES_SUCCESS';
export const FETCH_TVSERIES_FAILED = 'FETCH_TVSERIES_FAILED';

export const SET_TVSERIES_CURRENT_PAGE = 'SET_TVSERIES_CURRENT_PAGE';

export const FETCH_TVSERIES_GENRES = 'FETCH_TVSERIES_GENRES';
export const FETCH_TVSERIES_GENRES_SUCCESS = 'FETCH_TVSERIES_GENRES_SUCCES';
export const FETCH_TVSERIES_GENRES_FAILED = 'FETCH_TVSERIES_GENRES_FAILED';


export const SET_TVSERIES_SELECTED_GENRES= 'SET_TVSERIES_SELECTED_GENRES';

export const SET_TVSERIES_SELECTED_GENRES_ID = 'SET_TVSERIES_SELECTED_GENRES_ID';

export const UPDATE_TVSERIES_GENRES = 'UPDATE_TVSERIES_GENRES';