export const FETCH_INFO = 'FETCH_INFO';
export const FETCH_INFO_SUCCESS = 'FETCH_INFO_SUCCESS';
export const FETCH_INFO_FAILED = 'FETCH_INFO_FAILED';

export const FETCH_CAST = 'FETCH_CAST';
export const FETCH_CAST_SUCCESS = 'FETCH_CAST_SUCCESS';
export const FETCH_CAST_FAILED = 'FETCH_CAST_FAILED';